### ISSUE TITLE
empty folders 4.26 and up

### ISSUE THREAD

**Issue by 1julietb1** [MarkusTheOrt/Spotify-Unreal-Controls#2]
Hi, I downloaded the 4.26, it generated an empty content folder. I have just 3 c++ files.
Tried with 4.26, 4.27, 5EA
Can you help?

**Comment by MarkusTheOrt** [comment]
Yes, this is actually expected behaviour. 

The Spotify API is integrated using a `UGameInstanceSubsystem`

You can access this in any Blueprint using the exposed functions: 
![Blueprint Functions showcase](https://user-images.githubusercontent.com/39794659/158276035-08d87422-823e-4b27-ab2b-c472178d11d5.png)

For the settings you can go into Project settings and set them there (this is handled by utilizing the `UDeveloperSettings` class.:
![Showing Project Settings](https://user-images.githubusercontent.com/39794659/158276115-db0b3589-8434-4796-90cb-0081035fc10d.png)

**Comment by MarkusTheOrt** [comment]
I fixed the empty folder on the 5.0 (`main`) branch.
The issue is with github not serving LFS files in the .zip download.
If you want to use the 4.26/4.27 clone the repository rather than the .zip download.
